### ISSUE TITLE
ntp client

### ISSUE THREAD

**Issue by kostyrev** [kbrebanov/ansible-ntp#1]
Hi, great role but
how do you configure ntp client in your infrastructure? Do you have a supplementary ntp client role?

**Comment by kbrebanov** [comment]
@kostyrevaa Actually, this is the role I use to configure NTP clients.

It sets up servers to synchronize with and restricts access to localhost only.
To use this as an NTP server, the access permissions would have to be configurable.

**Comment by kostyrev** [comment]
Nevermind. I switched to another role :)
